### PR TITLE
Allow reading/writing/removing from existing files

### PR DESCRIPTION
**Pull request by Serial-ATA**
Replace read/write/remove with read_from_path/write_from_path/remove_from_path and add read_from/write_to/remove_from so existing files can be used.

### CODE REVIEW

**Review by jxs — APPROVED** [review]

**Comment by jxs** [comment]
Hi there, thanks for your interest! Can you fix the issues reported by the CI?

**Comment by Serial-ATA** [comment]
fixed :)

**Review by rossnomann — APPROVED** [review]
Looks good

**Comment by rossnomann** [comment]
Merged in aa0fac2e7b5e73db2c10251d9c666cc64e1de22f

**Pull request closed without merging**
